ui: tape
browsers:
  - name: chrome
    version: 39..latest
  - name: firefox
    version: 34..latest
  - name: safari
    version: 8..latest
  - name: ie
    version: 11..latest
  - name: microsoftedge
    version: latest
  - name: opera
    version: 11..latest
  - name: iphone
    version: 8.0..latest
  - name: android
    version: 4.4..latest
